begin;

drop policy if exists "Anyone can view listing avatars" on storage.objects;
drop policy if exists "Anyone can view listing photos" on storage.objects;

update storage.buckets
set allowed_mime_types = array['image/png', 'image/jpeg']::text[]
where id in ('avatars', 'listing_avatars');

update storage.buckets
set allowed_mime_types = array['image/jpeg']::text[]
where id = 'listing_photos';

-- User media must be written through the authenticated server upload route so
-- files are normalised before they become canonical Storage objects.
drop policy if exists "Allow authenticated changes 1oj01fe_0" on storage.objects;
drop policy if exists "Allow authenticated changes 1oj01fe_1" on storage.objects;
drop policy if exists "Allow authenticated deletes 1oj01fe_0" on storage.objects;
drop policy if exists "Users can upload their own listing avatars" on storage.objects;
drop policy if exists "Users can update their own listing avatars" on storage.objects;
drop policy if exists "Users can delete their own listing avatars" on storage.objects;
drop policy if exists "Users can upload their own listing photos" on storage.objects;
drop policy if exists "Users can update their own listing photos" on storage.objects;
drop policy if exists "Users can delete their own listing photos" on storage.objects;

revoke insert, update on table public.profiles from authenticated;
revoke insert, update on table public.listings from authenticated;
revoke delete on table public.listings from authenticated;
revoke insert (id) on table public.listings from authenticated;
revoke insert (avatar, photos) on table public.listings from authenticated;
revoke update (avatar, photos) on table public.listings from authenticated;
revoke insert (avatar) on table public.profiles from authenticated;
revoke update (avatar) on table public.profiles from authenticated;

grant insert (id, first_name, is_newsletter_subscribed, preferred_locale)
  on table public.profiles to authenticated;
grant update (first_name, is_newsletter_subscribed, preferred_locale)
  on table public.profiles to authenticated;

grant insert (
  owner_id,
  name,
  description,
  location,
  accepted_items,
  rejected_items,
  links,
  visibility,
  type,
  country_code,
  area_name,
  is_stub
) on table public.listings to authenticated;
grant update (
  owner_id,
  name,
  description,
  location,
  accepted_items,
  rejected_items,
  links,
  visibility,
  type,
  country_code,
  area_name,
  is_stub
) on table public.listings to authenticated;

create table public.pending_media_uploads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bucket text not null check (bucket in ('listing_avatars', 'listing_photos')),
  path text not null,
  kind text not null check (kind in ('listing_avatar', 'listing_photo')),
  created_at timestamp with time zone not null default timezone('utc', now()),
  unique (bucket, path)
);

create index pending_media_uploads_active_lookup_idx
on public.pending_media_uploads (user_id, bucket, kind, created_at desc);

alter table public.pending_media_uploads enable row level security;

revoke all on table public.pending_media_uploads from anon, authenticated, public;
revoke all on sequence public.pending_media_uploads_id_seq from anon, authenticated, public;
grant select, insert, delete on table public.pending_media_uploads to service_role;
grant usage, select on sequence public.pending_media_uploads_id_seq to service_role;

drop function if exists public.append_listing_photo(text, text);
drop function if exists public.remove_listing_photo(text, text);
drop function if exists public.restore_listing_photos_after_failed_delete(
  text,
  uuid,
  text[],
  text[]
);

create or replace function public.append_listing_photo(
  p_listing_slug text,
  p_photo text,
  p_owner_id uuid
)
returns table (
  id bigint,
  photos text[]
)
language sql
set search_path = public
as $$
  update public.listings
  set photos = array_append(coalesce(public.listings.photos, array[]::text[]), p_photo)
  where public.listings.slug = p_listing_slug
    and public.listings.owner_id = p_owner_id
  returning public.listings.id, public.listings.photos;
$$;

revoke all on function public.append_listing_photo(text, text, uuid) from anon, authenticated, public;
grant execute on function public.append_listing_photo(text, text, uuid) to service_role;

create or replace function public.remove_listing_photo(
  p_listing_slug text,
  p_photo text,
  p_owner_id uuid
)
returns table (
  id bigint,
  photos text[]
)
language sql
set search_path = public
as $$
  update public.listings
  set photos = array_remove(coalesce(public.listings.photos, array[]::text[]), p_photo)
  where public.listings.slug = p_listing_slug
    and public.listings.owner_id = p_owner_id
    and p_photo = any(coalesce(public.listings.photos, array[]::text[]))
  returning public.listings.id, public.listings.photos;
$$;

revoke all on function public.remove_listing_photo(text, text, uuid) from anon, authenticated, public;
grant execute on function public.remove_listing_photo(text, text, uuid) to service_role;

create or replace function public.restore_listing_photos_after_failed_delete(
  p_listing_slug text,
  p_owner_id uuid,
  p_expected_photos text[],
  p_restore_photos text[]
)
returns table (
  id bigint,
  photos text[]
)
language sql
set search_path = public
as $$
  update public.listings
  set photos = coalesce(p_restore_photos, array[]::text[])
  where public.listings.slug = p_listing_slug
    and public.listings.owner_id = p_owner_id
    and coalesce(public.listings.photos, array[]::text[]) =
      coalesce(p_expected_photos, array[]::text[])
  returning public.listings.id, public.listings.photos;
$$;

revoke all on function public.restore_listing_photos_after_failed_delete(text, uuid, text[], text[])
  from anon, authenticated, public;
grant execute on function public.restore_listing_photos_after_failed_delete(text, uuid, text[], text[])
  to service_role;

create or replace function public.create_pending_media_upload(
  p_bucket text,
  p_kind text,
  p_path text,
  p_user_id uuid
)
returns void
language plpgsql
set search_path = public
as $$
begin
  if p_bucket not in ('listing_avatars', 'listing_photos') then
    raise exception 'invalid_pending_media_bucket'
      using errcode = '23514', constraint = 'pending_media_uploads_bucket_check';
  end if;

  if p_kind not in ('listing_avatar', 'listing_photo') then
    raise exception 'invalid_pending_media_kind'
      using errcode = '23514', constraint = 'pending_media_uploads_kind_check';
  end if;

  if (
    (p_kind = 'listing_avatar' and p_bucket <> 'listing_avatars')
    or (p_kind = 'listing_photo' and p_bucket <> 'listing_photos')
  ) then
    raise exception 'invalid_pending_media_bucket_kind_pair'
      using errcode = '23514', constraint = 'pending_media_uploads_bucket_kind_pair_check';
  end if;

  if p_kind = 'listing_avatar' then
    perform pg_advisory_xact_lock(
      hashtextextended('pending_listing_avatars:' || p_user_id::text, 0)
    );

    if (
      select count(*)
      from public.pending_media_uploads
      where user_id = p_user_id
        and bucket = 'listing_avatars'
        and kind = 'listing_avatar'
        and created_at >= now() - interval '1 day'
    ) >= 5 then
      raise exception 'max_pending_listing_avatars'
        using errcode = '23514', constraint = 'max_pending_listing_avatars';
    end if;
  elsif p_kind = 'listing_photo' then
    perform pg_advisory_xact_lock(
      hashtextextended('pending_listing_photos:' || p_user_id::text, 0)
    );

    if (
      select count(*)
      from public.pending_media_uploads
      where user_id = p_user_id
        and bucket = 'listing_photos'
        and kind = 'listing_photo'
        and created_at >= now() - interval '1 day'
    ) >= 5 then
      raise exception 'max_pending_listing_photos'
        using errcode = '23514', constraint = 'max_pending_listing_photos';
    end if;
  end if;

  insert into public.pending_media_uploads (bucket, kind, path, user_id)
  values (p_bucket, p_kind, p_path, p_user_id);
end;
$$;

revoke all on function public.create_pending_media_upload(text, text, text, uuid)
  from anon, authenticated, public;
grant execute on function public.create_pending_media_upload(text, text, text, uuid)
  to service_role;

create or replace function public.reorder_listing_media_references(
  p_listing_id bigint,
  p_owner_id uuid,
  p_avatar text,
  p_photos text[]
)
returns table (
  id bigint
)
language sql
set search_path = public
as $$
  update public.listings
  set
    avatar = nullif(btrim(p_avatar), ''),
    photos = coalesce(p_photos, array[]::text[])
  where public.listings.id = p_listing_id
    and public.listings.owner_id = p_owner_id
    and coalesce(public.listings.avatar, '') =
      coalesce(nullif(btrim(p_avatar), ''), '')
    and cardinality(coalesce(public.listings.photos, array[]::text[])) =
      cardinality(coalesce(p_photos, array[]::text[]))
    and coalesce(public.listings.photos, array[]::text[]) @>
      coalesce(p_photos, array[]::text[])
    and coalesce(public.listings.photos, array[]::text[]) <@
      coalesce(p_photos, array[]::text[])
  returning public.listings.id;
$$;

revoke all on function public.reorder_listing_media_references(bigint, uuid, text, text[])
  from anon, authenticated, public;
grant execute on function public.reorder_listing_media_references(bigint, uuid, text, text[])
  to service_role;

create or replace function public.update_listing_with_media_references(
  p_listing_id bigint,
  p_owner_id uuid,
  p_type text,
  p_name text,
  p_description text,
  p_location text,
  p_area_name text,
  p_country_code text,
  p_accepted_items text[],
  p_rejected_items text[],
  p_links text[],
  p_visibility boolean,
  p_is_stub boolean,
  p_avatar text,
  p_photos text[]
)
returns table (
  id bigint,
  slug text,
  type text
)
language sql
set search_path = public
as $$
  update public.listings
  set
    type = p_type,
    name = p_name,
    description = p_description,
    location = p_location::extensions.geography,
    area_name = p_area_name,
    country_code = p_country_code,
    accepted_items = p_accepted_items,
    rejected_items = p_rejected_items,
    links = p_links,
    visibility = p_visibility,
    is_stub = coalesce(p_is_stub, public.listings.is_stub),
    avatar = nullif(btrim(p_avatar), ''),
    photos = coalesce(p_photos, array[]::text[])
  where public.listings.id = p_listing_id
    and public.listings.owner_id = p_owner_id
    and (
      coalesce(p_is_stub, public.listings.is_stub, false) = false
      or exists (
        select 1
        from public.profiles
        where profiles.id = p_owner_id
          and profiles.is_admin = true
      )
    )
    and coalesce(public.listings.avatar, '') =
      coalesce(nullif(btrim(p_avatar), ''), '')
    and cardinality(coalesce(public.listings.photos, array[]::text[])) =
      cardinality(coalesce(p_photos, array[]::text[]))
    and coalesce(public.listings.photos, array[]::text[]) @>
      coalesce(p_photos, array[]::text[])
    and coalesce(public.listings.photos, array[]::text[]) <@
      coalesce(p_photos, array[]::text[])
  returning public.listings.id, public.listings.slug, public.listings.type;
$$;

revoke all on function public.update_listing_with_media_references(
  bigint,
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  text[],
  text[],
  text[],
  boolean,
  boolean,
  text,
  text[]
) from anon, authenticated, public;
grant execute on function public.update_listing_with_media_references(
  bigint,
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  text[],
  text[],
  text[],
  boolean,
  boolean,
  text,
  text[]
) to service_role;

create or replace function public.attach_pending_listing_media(
  p_listing_id bigint,
  p_owner_id uuid,
  p_avatar text,
  p_photos text[]
)
returns table (
  id bigint
)
language plpgsql
set search_path = public
as $$
declare
  normalised_avatar text := nullif(btrim(p_avatar), '');
  photo_paths text[] := coalesce(p_photos, array[]::text[]);
  deleted_count integer;
begin
  if cardinality(photo_paths) > 5 then
    raise exception 'max_photos_per_listing'
      using errcode = '23514', constraint = 'max_photos_per_listing';
  end if;

  if exists (
    select 1
    from unnest(photo_paths) as photo(path)
    where nullif(btrim(photo.path), '') is null
  ) then
    raise exception 'invalid_listing_photo_path'
      using errcode = '23514', constraint = 'valid_listing_photo_paths';
  end if;

  if (
    select count(*)
    from unnest(photo_paths) as photo(path)
  ) <> (
    select count(distinct photo.path)
    from unnest(photo_paths) as photo(path)
  ) then
    raise exception 'duplicate_listing_photo_path'
      using errcode = '23514', constraint = 'unique_listing_photo_paths';
  end if;

  perform 1
  from public.listings
  where listings.id = p_listing_id
    and listings.owner_id = p_owner_id
  for update;

  if not found then
    raise exception 'listing_media_attach_failed'
      using errcode = '23514', constraint = 'listing_media_attach_owner_check';
  end if;

  if normalised_avatar is not null then
    delete from public.pending_media_uploads
    where bucket = 'listing_avatars'
      and kind = 'listing_avatar'
      and path = normalised_avatar
      and user_id = p_owner_id;

    get diagnostics deleted_count = row_count;

    if deleted_count <> 1 then
      raise exception 'pending_listing_avatar_not_found'
        using errcode = '23514', constraint = 'pending_listing_avatar_owner_check';
    end if;
  end if;

  if cardinality(photo_paths) > 0 then
    delete from public.pending_media_uploads
    where bucket = 'listing_photos'
      and kind = 'listing_photo'
      and path = any(photo_paths)
      and user_id = p_owner_id;

    get diagnostics deleted_count = row_count;

    if deleted_count <> cardinality(photo_paths) then
      raise exception 'pending_listing_photos_not_found'
        using errcode = '23514', constraint = 'pending_listing_photos_owner_check';
    end if;
  end if;

  update public.listings
  set
    avatar = normalised_avatar,
    photos = photo_paths
  where listings.id = p_listing_id
    and listings.owner_id = p_owner_id;

  return query
  select p_listing_id;
end;
$$;

revoke all on function public.attach_pending_listing_media(bigint, uuid, text, text[])
  from anon, authenticated, public;
grant execute on function public.attach_pending_listing_media(bigint, uuid, text, text[])
  to service_role;

create or replace function private.test_cleanup_orphaned_files()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  file record;
begin
  raise notice 'Orphaned profile avatars:';
  for file in
    select name
    from storage.objects
    where bucket_id = 'avatars'
      and name not in (
        select avatar from public.profiles where avatar is not null
      )
  loop
    raise notice '%', file.name;
  end loop;

  raise notice 'Orphaned listing avatars:';
  for file in
    select name
    from storage.objects
    where bucket_id = 'listing_avatars'
      and name not in (
        select avatar from public.listings where avatar is not null
        union
        select path
        from public.pending_media_uploads
        where bucket = 'listing_avatars'
          and created_at >= now() - interval '1 day'
      )
  loop
    raise notice '%', file.name;
  end loop;

  raise notice 'Orphaned listing photos:';
  for file in
    select name
    from storage.objects
    where bucket_id = 'listing_photos'
      and name not in (
        select unnest(photos)
        from public.listings
        where photos is not null
        union
        select path
        from public.pending_media_uploads
        where bucket = 'listing_photos'
          and created_at >= now() - interval '1 day'
      )
  loop
    raise notice '%', file.name;
  end loop;
end;
$$;

commit;
