-- Prevent authenticated clients from supplying listing identity values.
-- Listing IDs should always be generated by the database sequence on create.

revoke insert (id) on table public.listings from authenticated;
